---
author:
 - name: Ewa Krzaklewska
   orcid: 0000-0002-7662-3373
   email: ewa.krzaklewska@uj.edu.pl
   affiliation: 
    - id: UJ
      name: Jagiellonian University, Institute of Sociology
      city: Kraków
      url: https://socjologia.uj.edu.pl/ewa-krzaklewska
 - name: Paulina Sekula
   orcid: 0000-0003-3239-8116
   email: paulina.sekula@uj.edu.pl
   affiliation: 
    - id: UJ
      name: Jagiellonian University, Institute of Sociology
      city: Kraków
      url: https://socjologia.uj.edu.pl/paulina-sekula

abstract: >
    This chapter explores how GEAM results can inform the design or revision of interventions within GEPs, highlighting key variables that have been instrumental in these processes. Most importantly, GEAM questionnaire gathers many variables that allow to verify and monitor the situation concerning the recommended areas of GEP interventions, such as 1. work-life balance and organisational culture, 2. gender balance in leadership and decision-making, 3. gender equality in recruitment and career progression and 4. measures against gender-based violence, including sexual harassment. GEAM results can be an appropriate complement to the existing sex-disaggregated administrative data and qualitative data.  
---

# Using GEAM Data for GEP Design or Revision

Improving gender equality should be an ongoing process. Therefore, the monitoring and evaluation of the progress are an essential phase of a GEP lifecycle. In their GEPs organisations should detail not only the set of activities that are required to achieve the defined aims, but also specific indicators to measure the achievement of these aims. Relevant indicators should be developed, regularly verified and communicated in GEP progress reports [@europeancommissionHorizon2021]. The GEAM tool can be used to verify some of these indicators, both quantitatively and qualitatively as it gathers feedback and inputs from staff and students on the organisational working culture, the perception and experiences of gender (in)equality in the organisation, organisational practices promoting gender equality, as well as sexist attitudes and behaviours. The GEAM questionnaire gathers many variables that allow to verify and monitor the situation concerning 1. work-life balance and organisational culture, 2. gender balance in leadership and decision-making, 3. gender equality in recruitment and career progression and 4. measures against gender-based violence, including sexual harassment. It does not cover the fifth recommended area of GEP intervention - inclusion of the sex/gender dimension into research and teaching content. However, the student and employee GEAM questionnaires can be adapted by adding a few questions or items to the existing questions tailored to the organisational needs – or to monitor specific action in the GEP.

GEAM results can be an appropriate complement to the existing sex-disaggregated administrative data and qualitative data, e. g. from individual or group interviews. Thus, the use of the GEAM survey in an organisation facilitates the fulfilment of the Horizon Europe GEP minimum mandatory process-related requirement to regularly collect, analyse and report sex-disaggregated data on personnel. With the module on “Training”, the survey also allows to verify the intake among the members of the organisational community of awareness-raising and training activities on gender equality and unconscious gender biases, which also need to be organised according to EU requirements.

In what follows, we introduce selected variables that are good indicators of recommended four areas of GEP intervention. GEAM, though, offers many more indicators that are presented here and could be useful for GEP monitoring.

**Recommended thematic GEP building blocks**

Considering the mandatory GEP process-related requirements GEAM directly answers to the requirement of data collection and monitoring – providing additional data to monitor GEP implementation with selected indicators. It also covers the topic of training participation in regards to specific topics of the training and allows to monitor the barriers in participation. Considering recommended areas, GEAM covers 4 out of 5 of them, leaving out the area of Integration of the gender dimension into research and teaching content. All other areas are well covered in indicated GEAM sections (see @tbl-ec-eligibility-geam).

+:---------------------------------------------------------------------------+:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **GEP eligibility criterion**                                              | **Coverage in GEAM sections**                                                                                                                                                                 |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **MANDATORY**                                                              |                                                                                                                                                                                               |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Publication and official endorsement of the GEP**                        | Questions evaluating organization’s commitment to gender equality (OCPER001)                                                                                                                  |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **GEP has dedicated resources**                                            | Not included                                                                                                                                                                                  |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Data collection and monitoring**                                         | GEAM as a tool for data collection and monitoring of GEP outcomes and impact                                                                                                                  |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Training**                                                               | Working conditions – Training\                                                                                                                                                                |
|                                                                            | GEAM includes questions on unconscious bias, equality, diversity, and inclusion training; Sexual and/or sexist or gender harassment                                                           |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **RECOMMENDED**                                                            |                                                                                                                                                                                               |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Work-life balance and organisational culture**                           | Working Conditions - Work-life balance;                                                                                                                                                       |
|                                                                            |                                                                                                                                                                                               |
|                                                                            | Working Conditions - Flexible working time and teleworking arrangements, training                                                                                                             |
|                                                                            |                                                                                                                                                                                               |
|                                                                            | Working Conditions - Caring Responsibilities, Working Conditions - Parental Leave, Organisational Culture and Climate - Working Culture, Organisational Culture and Climate - Gender Equality |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Gender balance in leadership and decision-making**                       | Working conditions - About your current job; Organisational Culture and Climate - Working Culture                                                                                             |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Gender equality in recruitment and career progression**                  | Working conditions - About your current job, Working Conditions - Recruitment and Promotion, Working Conditions - Training                                                                    |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Integration of the gender dimension into research and teaching content** | Not covered                                                                                                                                                                                   |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Measures against gender-based violence including sexual harassment**     | Behavior - Bullying, Harassment, Microagressions  (with the use of selected questions from UniSafe questionnaire on gender-based violence)                                                    |
+----------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Coverage of areas of action mandatory and recommended by EU eligibility criteria in GEAM (own elaboration) {#tbl-ec-eligibility-geam}

## Work-life balance and organisational culture

### Work-life balance

The GEAM questionnaire extensively covers issues related to work-life balance. The areas that are well covered include topics such as work flexibility, parental leave support, and workload management. Most of all, GEAM includes several variables that would allow us to see the characteristics of the care engagement by the employees; it includes questions on having children, being a single parent, and providing care to adult persons. Such information allows us to see if those who are engaged in care face more challenges at work and thus should receive adequate support from the institution. Such solutions can be included in the GEP as possible interventions.

The GEAM allows to check for the difficulties in managing family and work providing institutions with adequate indicators. The questions from ISSP on work-family conflict are good indicators for work-life balance and could be analysed separately for men and women, those having diverse care duties, but also for different positions in the university.

This question (WorkFamConfISSP) has four statements, first two relate to impact of personal life on work, and the other two relate to intervention of work into personal life:

+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+
| Code              | Question / Sub-questions                                                                                                  | Response                     |
+===================+===========================================================================================================================+==============================+
| `WorkFamConfISSP` | How often has each of the following happened to you during the past three months?                                         | \[1\] Several times a week\  |
|                   |                                                                                                                           | \[2\] Several times a month\ |
|                   |                                                                                                                           | \[3\] Once or twice\         |
|                   |                                                                                                                           | \[4\] Never                  |
+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+
|                   | I have found it difficult to concentrate at work because of my personal commitments.                                      |                              |
+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+
|                   | I have arrived at work too tired to function well because of household work.                                              |                              |
+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+
|                   | It has been difficult for me to fulfil my commitments in my personal life because of the amount of time I spent on my job |                              |
+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+
|                   | I have come home from work too tired to do the chores which need to be done.                                              |                              |
+-------------------+---------------------------------------------------------------------------------------------------------------------------+------------------------------+

: Work-family conflict scale

The analysis of the statements indicates for strong impact of work on family life, with most respondents agreeing that work intervenes in their personal life. The analysis of the statements between different groups indicated, for example, that academic teachers reported much more often than other workers groups that it has been difficult for them to fulfil my commitments in personal life because of the amount of time spent on the job. There is no statistically significant difference between women and men in regards to this statement.
