
project:
  type: book
  output-dir: _book

book:
  title: "Statistical Analysis for Inclusive Gender Equality"
  subtitle: "Practical Guidance for Analysing GEAM Data"
  date: today
  cover-image: images/cover-page-design.jpg
  favicon: images/cover-page-design.jpg
  site-url: https://geamtool.eu/analysis
  repo-url: https://github.com/InspireQualityeu/geam-analysis-book
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - part: "Part I: Statistical techniques" 
      chapters: 
      - 02-summary-respondents.qmd
      - 03-detecting-gaps.qmd
      - 04-compare-in-time.qmd
      - 06-intersectional-analysis.qmd
    - part: "Part II: Thematic Analysis"
      chapters: 
      - 07-geam-data-for-geps.qmd
      - 08-careers.qmd
      - 09-culture-climate.qmd
  appendices:  
    - 99-annex-i-desc-variables.qmd
    
  author:
  - name: Jörg Müller
    orcid: 0000-0001-7727-2117
    email: jmuller@uoc.edu
    affiliation: 
      - id: uoc
        name: Universitat Oberta de Catalunya
        city: Barcelona
        url: www.gender-ict.net
  - name: Dalia Argudo
    email: dalia.argudo@notus-asr.org
    affiliation: 
        - id: notus
          name: Notus, S.L.
          city: Barcelona
          url: www.notus-asr.org
  - name: Ewa Krzaklewska
    orcid: 0000-0002-7662-3373
    email: ewa.krzaklewska@uj.edu.pl
    affiliation: 
        - id: UJ
          name: Jagiellonian University, Institute of Sociology
          city: Kraków
          url: https://socjologia.uj.edu.pl/ewa-krzaklewska
  - name: Paulina Sekula
    orcid: 0000-0003-3239-8116
    email: paulina.sekula@uj.edu.pl
    affiliation: 
        - id: UJ
          name: Jagiellonian University, Institute of Sociology
          city: Kraków
          url: https://socjologia.uj.edu.pl/paulina-sekula
        
abstract: > 
  This manual aims to guide the statistical analysis of data generated by the GEAM questionnaire. It seeks to inspire and guide survey users in conducting statistical analysis beyond the basic descriptive. It is aimed at members of gender equality working groups (practitioners, gender specialists, administrative staff) who have collected data with GEAM in their organisation, but are unsure how to analyse it in more detail. Each chapter is a collaboration between equality practitioners and statisticians, allowing examples from different contexts to be included. It also provides a combination of R code, results, and their interpretation for practical use.
  
keywords:
  - Gender Equality Plan
  - Gender Equaliy Audit 
  - Equality Data Monitoring 
  - Intersectionality
  - Descriptive statistics
  - Statistical analysis

bibliography: references.bib
reference-location: margin
citation-location: document
tbl-cap-location: margin
fig-cap-location: margin
cap-location: margin

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    df-print: kable
  pdf:
    documentclass: scrbook
    include-in-header:
    - custom-header.tex
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github


editor: source
  
license: "CC BY NC"

copyright: 
  holder: INSPIRE Project Consortium
  year: 2025
  
funding: "This work has received funding under the European Union's Horizon Europe research and innovation programme under grant agreement No 101058537."



    
    