
project:
  type: book

book:

  title: "GEAM Analysis Handbook"
  author: "INSPIRE Project"
  date: "11/27/2024"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
    include-in-header:
    - custom-header.html


  pdf:
    documentclass: scrreprt
    include-in-header:
    - custom-header.tex
   
editor: visual


    
    