# Preface {.unnumbered}

 This book guides the statistical analysis of data collected with the Gender Equality Audit and Monitoring (GEAM) questionnaire. It seeks to inspire and empower users to perform statistical analyses beyond basic descriptive statistics, delving deeper into the underlying thematic issues.

It is intended for members of gender equality working groups, including professionals, gender specialists, administrative staff, and other stakeholders who have collected data using GEAM in their organisations but are uncertain about how to analyse it in greater depth.

Each chapter represents a collaboration between gender equality practitioners and academic statisticians and data analysts. Cases use real-world data from different Higher Eduaction organisations across Europe. Running thematic analysis side by side with the R code used, faciliates to kick-start similar analysis in different organisations. 

The statistical analyses presented in this manual encompass methodologies ranging from univariate and bivariate analyses to describe general patterns, to more advanced techniques such as multivariate analysis, logistic and linear regressions, hypothesis testing, and others. Modern data visualisation tools are also covered, enabling results to be represented in a clear and accessible manner. All of this aims to equip users with analytical skills to extract meaningful and evidence-based conclusions, essential for implementing policies and actions to promote gender equality.

The development of GEAM questionnaire framework began during the ACT project [Communities of PrACTice for Accelerating Gender Equality and Institutional Change in Research and Innovation across Europe (2018–2021)](https://www.act-on-gender.eu/).Subsequently, as part of the INSPIRE project [Building Europe’s Centre of Excellence on Inclusive Gender Equality in R&I](https://www.inspirequality.eu/), GEAM has adapted to better address the needs of academics, administrative staff, and university students across various organisations.

In this manual, users will find not only a technical resource but also a starting point for fostering an organisational culture rooted in gender equality through informed analysis and evidence-based decision-making.

## Acknowledgements {.unnumbered}

The editors want to thank especially all organisations that have run the GEAM survey previously and provided access to their data for the elaboration of this book. 
